### PR TITLE
Seeding

### PR DESCRIPTION
**Pull request by jeyrey**
This seeds some default data

### CODE REVIEW

**Comment by zzma** [comment]
Looks like some of the tests are failing now. Please fix.

**Comment by jeyrey** [comment]
The tests have a lot of assumptions about starting with an empty database. Lots of their functionality will be lost anyway when we add a separate email server. Do you want me to fix broken tests now or disable them for now?

**Comment by zzma** [comment]
@jeyrey - any update on this? Were you able to get the test environment setup properly? LMK if I can help with this

**Comment by jeyrey** [comment]
@zzma The tests pass locally but not on travis. You are welcome to take a look

**Pull request merged**
